from .models import users_model
from .models.cursive_printing_models.modes_model import CursivePrintingModes
from .models.cursive_printing_models.words_model import CursivePrintingWords
from .models.cursive_printing_models.statistics_model import CursivePrintingStatistics
from .models.english_models.words_model import EnglishWords
from .models.english_models.topics_model import EnglishTopics
from .models.english_models.texts_model import EnglishTexts
from .models.english_models.statistic_model import EnglishStatistics
from .models.clicker_models.statistics_model import ClickerStatistics
